---
apiVersion: v1
kind: Service
metadata:
  name: user-server
  labels:
    app: user-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: user-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
spec:
  selector:
    matchLabels:
      app: user-server
  replicas: 2
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
      - name: user-server
        image: how2die/user-server
        env:
        - name: NODE_ENV 
          value: production
        - name: AUTH_HOST
          value: auth-server
        - name: AUTH_PORT
          value: "8080"
        - name: DB_DATABASE
          value: user
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
